// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.zouni.netty.protobuf.nano;

@SuppressWarnings("hiding")
public interface ProtoMsg {

  public static final class MessageRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile MessageRequest[] _emptyArray;
    public static MessageRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new MessageRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // uint64 msg_id = 1;
    public long msgId;

    // string from = 2;
    public String from;

    // string to = 3;
    public String to;

    // int64 time = 4;
    public long time;

    // uint32 msg_type = 5;
    public int msgType;

    // string content = 6;
    public String content;

    // string url = 7;
    public String url;

    // string property = 8;
    public String property;

    // string from_nick = 9;
    public String fromNick;

    // string json = 10;
    public String json;

    public MessageRequest() {
      clear();
    }

    public MessageRequest clear() {
      msgId = 0L;
      from = "";
      to = "";
      time = 0L;
      msgType = 0;
      content = "";
      url = "";
      property = "";
      fromNick = "";
      json = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.msgId != 0L) {
        output.writeUInt64(1, this.msgId);
      }
      if (!this.from.equals("")) {
        output.writeString(2, this.from);
      }
      if (!this.to.equals("")) {
        output.writeString(3, this.to);
      }
      if (this.time != 0L) {
        output.writeInt64(4, this.time);
      }
      if (this.msgType != 0) {
        output.writeUInt32(5, this.msgType);
      }
      if (!this.content.equals("")) {
        output.writeString(6, this.content);
      }
      if (!this.url.equals("")) {
        output.writeString(7, this.url);
      }
      if (!this.property.equals("")) {
        output.writeString(8, this.property);
      }
      if (!this.fromNick.equals("")) {
        output.writeString(9, this.fromNick);
      }
      if (!this.json.equals("")) {
        output.writeString(10, this.json);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.msgId != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.msgId);
      }
      if (!this.from.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.from);
      }
      if (!this.to.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.to);
      }
      if (this.time != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, this.time);
      }
      if (this.msgType != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(5, this.msgType);
      }
      if (!this.content.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.content);
      }
      if (!this.url.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.url);
      }
      if (!this.property.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.property);
      }
      if (!this.fromNick.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.fromNick);
      }
      if (!this.json.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(10, this.json);
      }
      return size;
    }

    @Override
    public MessageRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.msgId = input.readUInt64();
            break;
          }
          case 18: {
            this.from = input.readString();
            break;
          }
          case 26: {
            this.to = input.readString();
            break;
          }
          case 32: {
            this.time = input.readInt64();
            break;
          }
          case 40: {
            this.msgType = input.readUInt32();
            break;
          }
          case 50: {
            this.content = input.readString();
            break;
          }
          case 58: {
            this.url = input.readString();
            break;
          }
          case 66: {
            this.property = input.readString();
            break;
          }
          case 74: {
            this.fromNick = input.readString();
            break;
          }
          case 82: {
            this.json = input.readString();
            break;
          }
        }
      }
    }

    public static MessageRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new MessageRequest(), data);
    }

    public static MessageRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new MessageRequest().mergeFrom(input);
    }
  }
}
